MvcOnlineTicariOtomasyon/Models/Classes/Current.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Classes
{
    public class Current
    {
        //Current=CARi,Akım
        [Key]
        public int CurrentId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30, ErrorMessage = "En Fazla 30 Karakter yazabilirsiniz.")]
        public string CurrentName { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz!")]
        public string CurrentSurname { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(13)]
        public string CurrentCity { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50, ErrorMessage = "50 Karakterden Fazla Olamaz.")]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz!")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail Adresi Geçerli Değildir.")]
        public string CurrentMail { get; set; }


        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string CurrentPassword { get; set; }

        public bool CurrentStatus { get; set; }
        public ICollection<SalesTransaction> SalesTransactions { get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/CurrentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Classes;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class CurrentController : Controller
    {
        // GET: Current
        Context co = new Context();
        public ActionResult Index()
        {
            var values = co.Currents.Where(x => x.CurrentStatus == true).ToList();
            return View(values);
        }
        [HttpGet]
        public ActionResult CurrentAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CurrentAdd(Current c)
        {
            c.CurrentStatus = true;
            co.Currents.Add(c);
            co.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CurrentDelete(int id)
        {
            var cr = co.Currents.Find(id);
            cr.CurrentStatus = false;
            co.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CurrentEdit(int id)
        {
            var cr = co.Currents.Find(id);
            return View("CurrentEdit", cr);
        }

        public ActionResult CurrentUpdate(Current c)
        {
            if (!ModelState.IsValid)
            {
                return View("CurrentEdit");
            }
            var crr = co.Currents.Find(c.CurrentId);
            crr.CurrentName = c.CurrentName;
            crr.CurrentSurname = c.CurrentSurname;
            crr.CurrentMail = c.CurrentMail;
            crr.CurrentCity = c.CurrentCity;
            co.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CustomerSales(int id)
        {
            var values = co.SalesTransactions.Where(x => x.CurrentID == id).ToList();
            var cr = co.Currents.Where(x => x.CurrentId == id).Select(y => y.CurrentName + " " + y.CurrentSurname).FirstOrDefault();
            ViewBag.crrnt= cr;
            return View(values);
        }

    }
}

MvcOnlineTicariOtomasyon/Views/Current/CurrentAdd.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Current
@{
    ViewBag.Title = "CurrentAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Yeni Cari Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Cari Adı :")
    @Html.TextBoxFor(x => x.CurrentName, new { @class = "form-control" })
    <br />
    @Html.Label("Cari Soyadı :")
    @Html.TextBoxFor(x => x.CurrentSurname, new { @class = "form-control" })
    <br />
    @Html.Label("Cari Şehri :")
    @Html.TextBoxFor(x => x.CurrentCity, new { @class = "form-control" })
    <br />
    @Html.Label("Cari Mail :")
    @Html.TextBoxFor(x => x.CurrentMail, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">KAYDET</button>
</form>

MvcOnlineTicariOtomasyon/Views/Current/CurrentEdit.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Current
@{
    ViewBag.Title = "CurrentEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Cari Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("CurrentUpdate", "Current", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.CurrentId)
        @Html.Label("Cari Ad:")
        @Html.TextBoxFor(x => x.CurrentName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CurrentName, "", new { @style = "color-red" })
        <br />
        @Html.Label("Cari Soyad:")
        @Html.TextBoxFor(x => x.CurrentSurname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CurrentName, "", new { @style = "color-red" })
        <br />
        @Html.Label("Cari Şehir:")
        @Html.TextBoxFor(x => x.CurrentCity, new { @class = "form-control" })
        <br />
        @Html.Label("Cari Mail:")
        @Html.TextBoxFor(x => x.CurrentMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CurrentMail, "", new { @style = "color-red" })
    </div>
    <br />
    <button class="btn btn-success">GÜNCELLE</button>
}

MvcOnlineTicariOtomasyon/Views/Current/CustomerSales.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<SalesTransaction>
@{
    ViewBag.Title = "CustomerSales";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Departman Personel Satış</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Cari Adı: @ViewBag.crrnt</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>Satış ID</th>
        <th>Ürün</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.SalesTransactionId</td>
            <td>@x.Product.ProductName</td>
            <td>@x.Personnel.PersonnelName @x.Personnel.PersonnelSurname</td>
            <td>@x.SalesPrice</td>
            <td>@x.SalesPiece</td>
            <td>@x.SalesTotalAmount</td>
            <td>@x.SalesDateTime</td>
            <td><a href="#" class="btn btn-default" style="background-color:coral">Yazdır</a></td>
        </tr>
    }

</table>

MvcOnlineTicariOtomasyon/Views/Current/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<Current>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-hover">
    <tr>
        <th>Cari ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Mail</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>DETAYLAR</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.CurrentId</td>
            <td>@x.CurrentName</td>
            <td>@x.CurrentSurname</td>
            <td>@x.CurrentCity</td>
            <td>@x.CurrentMail</td>
            <td><a href="/Current/CurrentDelete/@x.CurrentId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Current/CurrentEdit/@x.CurrentId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Current/CustomerSales/@x.CurrentId" class="btn btn-info" style="background-color:lightblue; color:black">Satış Geçmişi</a></td>
        </tr>
    }
</table>
<a href="/Current/CurrentAdd" class="btn btn-primary">Yeni Cari Ekle</a>