MvcOnlineTicariOtomasyon/Models/Classes/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;

namespace MvcOnlineTicariOtomasyon.Models.Classes
{
    public class Department
    {
        [Key]
        public int DepartmentId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DepartmentName { get; set; }
        public bool DepartmentStatus { get; set; }
        public ICollection<Personnel> Personnels { get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Classes;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        // GET: Department
        Context co = new Context();
        public ActionResult Index()
        {
            var values = co.Departments.Where(x => x.DepartmentStatus == true).ToList();
            return View(values);
        }
        [HttpGet]
        public ActionResult DepartmentAdd()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DepartmentAdd(Department d)
        {
            co.Departments.Add(d);
            co.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmentDelete(int id)
        {
            var dep = co.Departments.Find(id);
            dep.DepartmentStatus = false;
            co.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmentEdit(int id)
        {
            var dpt = co.Departments.Find(id);
            return View("DepartmentEdit", dpt);
        }

        public ActionResult DepartmentUpdate(Department d)
        {
            var dept = co.Departments.Find(d.DepartmentId);
            dept.DepartmentName = d.DepartmentName;
            co.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult DepartmentDetail(int id)
        {
            var val = co.Personnels.Where(x => x.PersonnelId == id).ToList();
            var dpt = co.Departments.Where(x => x.DepartmentId == id).Select(y => y.DepartmentName).FirstOrDefault();
            ViewBag.d = dpt;
            return View(val);
        }
        public ActionResult DepartmentPersonnelSales(int id)
        {
            var values = co.SalesTransactions.Where(x => x.PersonnelID == id).ToList();

            var prs = co.Personnels.Where(x => x.PersonnelId == id).Select(y => y.PersonnelName + " " + y.PersonnelSurname).FirstOrDefault();
            ViewBag.dpers = prs;

            return View(values);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Department/DepartmentAdd.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Department
@{
    ViewBag.Title = "DepartmentAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Yeni Departman Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Departman Adı :")
    @Html.TextBoxFor(x => x.DepartmentName, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">KAYDET</button>
</form>

MvcOnlineTicariOtomasyon/Views/Department/DepartmentDetail.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<Personnel>
@{
    ViewBag.Title = "DepartmentDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Department Detay Sayfası</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Departman Adı: @ViewBag.d</li>
</ol>
<table class="table table-hover">
    <tr>

        <th>Personel</th>
        <th>Satışlar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.PersonnelName @x.PersonnelSurname</td>
            <td><a href="/Department/DepartmentPersonnelSales/@x.PersonnelId" class="btn btn-default" style="background-color:darkcyan">Satışlar</a></td>
        </tr>
    }

</table>

MvcOnlineTicariOtomasyon/Views/Department/DepartmentEdit.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Department
@{
    ViewBag.Title = "DepartmentEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kategori Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("DepartmentUpdate", "Department", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Departman Ad:")
        @Html.TextBoxFor(x => x.DepartmentName, new { @class = "form-control" })
        @Html.HiddenFor(x => x.DepartmentId)
    </div>
    <br />
    <button class="btn btn-success">GÜNCELLE</button>
}

MvcOnlineTicariOtomasyon/Views/Department/DepartmentPersonnelSales.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<SalesTransaction>
@{
    ViewBag.Title = "DepartmentPersonnelSales";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Departman Personel Satış</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel Adı: @ViewBag.dpers</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Product.ProductName</td>
            <td>@x.Current.CurrentName @x.Current.CurrentSurname</td>
            <td>@x.SalesPrice ₺</td>
            <td>@x.SalesPiece</td>
            <td>@x.SalesTotalAmount</td>
            <td>@x.SalesDateTime</td>
            <td><a href="#" class="btn btn-default" style="background-color:coral">Yazdır</a></td>
        </tr>
    }

</table>

MvcOnlineTicariOtomasyon/Views/Department/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<Department>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>Departman Adı</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>DETAYLAR</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.DepartmentId</td>
            <td>@x.DepartmentName</td>
            <td><a href="/Department/DepartmentDelete/@x.DepartmentId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Department/DepartmentEdit/@x.DepartmentId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Department/DepartmentDetail/@x.DepartmentId" class="btn btn-info" style="background-color:lightblue; color:black">Detay</a></td>

        </tr>
    }

</table>
<a href="/Department/DepartmentAdd" class="btn btn-primary">Yeni Kategori Ekle</a>