MvcOnlineTicariOtomasyon/Models/Classes/Bill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Classes
{
    public class Bill
    {
        //Bill=Fatura
        [Key]
        public int BillId { get; set; }

        [Column(TypeName = "Char")]
        [StringLength(1)]
        public string BillSerialNumber { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(6)]
        public string BillOrderNumber { get; set; }
        public DateTime BillDatetime { get; set; }

        //Vergi Dairesi=Tax Office
        [Column(TypeName = "Varchar")]
        [StringLength(60)]
        public string BillTaxOffice { get; set; }

        [Column(TypeName = "char")]
        [StringLength(5)]
        public string BillClock { get; set; }

        //Deliverer=Teslim Eden
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string BillDeliverer { get; set; }


        //Teslim Alan=recipient
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string BillRecipient { get; set; }

        public decimal BillTotalAmount { get; set; }
        public ICollection<BillPencil> BillPencils { get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Classes;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class BillController : Controller
    {
        // GET: Bill
        Context co = new Context();
        public ActionResult Index()
        {
            var list = co.Bills.ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult BillAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult BillAdd(Bill b)
        {
            co.Bills.Add(b);
            co.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult BillEdit(int id)
        {
            var bill = co.Bills.Find(id);
            return View("BillEdit", bill);
        }
        public ActionResult BillUpdate(Bill b)
        {
            var bil = co.Bills.Find(b.BillId);
            bil.BillSerialNumber = b.BillSerialNumber;
            bil.BillOrderNumber = b.BillOrderNumber;
            bil.BillClock = b.BillClock;
            bil.BillDatetime = b.BillDatetime;
            bil.BillTaxOffice = b.BillTaxOffice;
            bil.BillDeliverer = b.BillDeliverer;
            bil.BillRecipient = b.BillRecipient;
            co.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult BillDetail(int id)
        {
            var values = co.BillPencils.Where(x => x.BillId == id).ToList();
            return View(values);
        }
        [HttpGet]
        public ActionResult NewPencil()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Newpencil(BillPencil p)
        {
            co.BillPencils.Add(p);
            co.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Dynamic()
        {
            Class3 cs = new Class3();
            cs.value1 = co.Bills.ToList();
            cs.value2 = co.BillPencils.ToList();
            return View(cs);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Bill/BillAdd.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Bill
@{
    ViewBag.Title = "BillAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Yeni Fatura Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Fatura Seri No :")
    @Html.TextBoxFor(x => x.BillSerialNumber, new { @class = "form-control" })
    <br />
    @Html.Label("Fatura Sıra No :")
    @Html.TextBoxFor(x => x.BillOrderNumber, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih :")
    @Html.TextBoxFor(x => x.BillDatetime, new { @class = "form-control" })
    <br />
    @Html.Label("Saat :")
    @Html.TextBoxFor(x => x.BillClock, new { @class = "form-control" })
    <br />
    @Html.Label("Vergi Dairesi :")
    @Html.TextBoxFor(x => x.BillTaxOffice, new { @class = "form-control" })
    <br />
    @Html.Label("Teslim Eden :")
    @Html.TextBoxFor(x => x.BillDeliverer, new { @class = "form-control" })
    <br />
    @Html.Label("Teslim Alan :")
    @Html.TextBoxFor(x => x.BillRecipient, new { @class = "form-control" })

    <br />
    <button class="btn btn-info">KAYDET</button>
</form>

MvcOnlineTicariOtomasyon/Views/Bill/BillDetail.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<BillPencil>
@{
    ViewBag.Title = "BillDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Fatura Kalemleri Sayfası</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active"></li>
</ol>
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Açıklama</th>
        <th>Miktar</th>
        <th>Birim Fiyat</th>
        <th>Tutar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.BillPencilId</td>
            <td>@x.BillPencilExplanation</td>
            <td>@x.BillPencilAmount</td>
            <td>@x.BillPencilUnitPrice</td>
            <td>@x.BillPencilTotal</td>
        </tr>
    }

</table>
<a href="/Bill/NewPencil/" class="btn btn-default" style="background-color:darkcyan; color:white">Yeni Kalem Girişi</a>

MvcOnlineTicariOtomasyon/Views/Bill/BillEdit.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Bill
@{
    ViewBag.Title = "BillEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Fatura Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("BillUpdate", "Bill", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.BillId)
        @Html.Label("Fatura Seri No : ")
        @Html.TextBoxFor(x => x.BillSerialNumber, new { @class = "form-control" })
        <br />
        @Html.Label("Fatura Sıra No : ")
        @Html.TextBoxFor(x => x.BillOrderNumber, new { @class = "form-control" })
        <br />
        @Html.Label("Vergi Dairesi : ")
        @Html.TextBoxFor(x => x.BillTaxOffice, new { @class = "form-control" })
        <br />
        @Html.Label("Tarih : ")
        @Html.TextBoxFor(x => x.BillDatetime, new { @class = "form-control" })
        <br />
        @Html.Label("Saat : ")
        @Html.TextBoxFor(x => x.BillClock, new { @class = "form-control" })
        <br />
        @Html.Label("Teslim Eden : ")
        @Html.TextBoxFor(x => x.BillDeliverer, new { @class = "form-control" })
        <br />
        @Html.Label("Teslim Alan : ")
        @Html.TextBoxFor(x => x.BillRecipient, new { @class = "form-control" })
    </div>
    <br />
    <button class="btn btn-success">GÜNCELLE</button>
}

MvcOnlineTicariOtomasyon/Views/Bill/Dynamic.cshtml
@{
    ViewBag.Title = "Dynamic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dynamic</h2>

MvcOnlineTicariOtomasyon/Views/Bill/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<Bill>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>Seri Sıra No</th>
        <th>Tarih</th>
        <th>Saat</th>
        <th>Toplam</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
        <th>Popup Liste</th>
        <th>Yeni Kalem</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.BillSerialNumber @x.BillOrderNumber</td>
            <td>@x.BillDatetime</td>
            <td>@x.BillClock</td>
            <td>@x.BillTotalAmount ₺</td>

            <td><a href="/Bill/BillEdit/@x.BillId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Bill/BillDetail/@x.BillId" class="btn btn-info" style="background-color:lightblue; color:black">Detay</a></td>
            <td><a href="/Bill/BillDetail/@x.BillId" class="btn btn-default" style="background-color:indianred; color:black">Popup_List</a></td>
            <td><a href="/Bill/BillDetail/@x.BillId" class="btn btn-info" style="background-color:deepskyblue; color:black">Y.Kalem</a></td>
        </tr>
    }
</table>
<a href="/Bill/BillAdd" class="btn btn-primary">Yeni Fatura Girişi</a>
<br />
<br />
<button type="button" class="btn btn-warning" style="background-color:antiquewhite" data-toggle="modal" data-target="#Modal1">Popup Penceresi</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Popup Diyalog Ekranı</h2>
            </div>
            <div class="modal-body">
                <table class="table table-hover">
                    <tr>
                        <td>Seri No</td>
                        <td>Sıra No</td>
                        <td>Tutar</td>
                    </tr>
                    @foreach (var x in Model)
                    {
                        <tr>
                            <td>@x.BillSerialNumber</td>
                            <td>@x.BillOrderNumber</td>
                            <td>@x.BillTotalAmount ₺</td>
                        </tr>
                    }

                </table>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Tamam</button>
            </div>
        </div>
    </div>
</div>

MvcOnlineTicariOtomasyon/Views/Bill/NewPencil.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.BillPencil
@{
    ViewBag.Title = "NewPencil";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Yeni Kalem Girişi</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Fatura Açıklama :")
    @Html.TextBoxFor(x => x.BillPencilExplanation, new { @class = "form-control" })
    <br />
    @Html.Label("Miktar :")
    @Html.TextBoxFor(x => x.BillPencilAmount, new { @class = "form-control" })
    <br />
    @Html.Label("Birim Fiyat :")
    @Html.TextBoxFor(x => x.BillPencilUnitPrice, new { @class = "form-control" })
    <br />
    @Html.Label("Tutar :")
    @Html.TextBoxFor(x => x.BillPencilTotal, new { @class = "form-control" })
    <br />
    @Html.Label("Fatura ID :")
    @Html.TextBoxFor(x => x.BillId, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">KAYDET</button>
</form>