MvcOnlineTicariOtomasyon/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Classes;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class StatisticsController : Controller
    {
        Context co = new Context();
        // GET: Statistics
        public ActionResult Index()
        {
            var value1 = co.Currents.Count().ToString();
            ViewBag.d1 = value1;
            var value2 = co.Products.Count().ToString();
            ViewBag.d2 = value2;
            var value3 = co.Personnels.Count().ToString();
            ViewBag.d3 = value3;
            var value4 = co.Categories.Count().ToString();
            ViewBag.d4 = value4;
            var value5 = co.Products.Sum(x => x.ProductStock).ToString();
            ViewBag.d5 = value5;

            var value6 = (from x in co.Products select x.ProductBrand).Distinct().Count().ToString();
            ViewBag.d6 = value6;

            var value7 = co.Products.Count(x => x.ProductStock <= 20).ToString();
            ViewBag.d7 = value7;

            var value8 = (from x in co.Products orderby x.ProductSalePrice descending select x.ProductName).FirstOrDefault();
            ViewBag.d8 = value8;

            var value9 = (from x in co.Products orderby x.ProductSalePrice ascending select x.ProductName).FirstOrDefault();
            ViewBag.d9 = value9;

            var value10 = co.Products.Count(x => x.ProductName == "Buzdolabı").ToString();
            ViewBag.d10 = value10;

            var value11 = co.Products.Count(x => x.ProductName == "Laptop").ToString();
            ViewBag.d11 = value11;

            var value12 = co.Products.GroupBy(x => x.ProductBrand).OrderByDescending(y => y.Count()).Select(z => z.Key).FirstOrDefault();
            ViewBag.d12 = value12;

            //value13 Sorgusunda satış tablosunda en fazla ürünün idsini bulduk ve adını ürünler tablosundan adını getirdik
            var value13 = co.Products.Where(d => d.ProductId == (co.SalesTransactions.GroupBy(x => x.ProductID).OrderByDescending(y => y.Count()).Select(z => z.Key).FirstOrDefault())).Select(k => k.ProductName).FirstOrDefault();
            ViewBag.d13 = value13;

            var value14 = co.SalesTransactions.Sum(x => x.SalesTotalAmount).ToString();
            ViewBag.d14 = value14;

            //Aynı Gün Yapılan Satış Sayısı
            DateTime todayy = DateTime.Today;
            var value15 = co.SalesTransactions.Count(x => x.SalesDateTime == todayy).ToString();
            ViewBag.d15 = value15;

            // Bugünkü satışların toplamı bugünün tarihine eşit olanları getir ve toplam tutarları topla
            if (Convert.ToInt32(value15) != 0)
            {
                var value16 = co.SalesTransactions.Where(x => x.SalesDateTime == todayy).Sum(y => y.SalesTotalAmount).ToString();
                ViewBag.d16 = value16;
            }
            else
            {
                ViewBag.d16 = value15;
            }


            return View();
        }
        public ActionResult SimpleTables()
        {
            var query = from x in co.Currents
                        group x by x.CurrentCity into g
                        select new GroupClass
                        {
                            City = g.Key,
                            Total = g.Count()
                        };

            return View(query.ToList());
        }
        public PartialViewResult Partial1()
        {
            var query2 = from x in co.Personnels
                         group x by x.Department.DepartmentName into g
                         select new GroupClass2
                         {
                             Departmentt = g.Key,
                             Number = g.Count()
                         };
            return PartialView(query2.ToList());
        }
        public PartialViewResult Partial2()
        {
            var query = co.Currents.ToList();
            return PartialView(query);
        }

        public PartialViewResult Partial3()
        {
            var query = co.Products.Take(10).ToList();
            return PartialView(query);
        }
        public PartialViewResult Partial4()
        {
            var query3 = (from x in co.Products
                          group x by x.ProductBrand into a
                          select new GroupClass3
                          {
                              Brand = a.Key,
                              Number = a.Count()
                          });
            return PartialView(query3.ToList());

        }
    }
}

MvcOnlineTicariOtomasyon/Views/Statistics/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <script src="js/zingchart.min.js"></script>
    <script src="js/zingchart.jquery.js"></script>
    <script src="js/jquery.easydropdown.js"></script>
    <script src="js/jquery.nicescroll.js"></script>

    <link href="css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <link href="~/web2/css/nav.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.d1</h3>
                    <p>Toplam Cari</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.d2</h3>
                    <p>Ürün Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.d3</h3>
                    <p>Personel Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.d4</h3>
                    <p>Kategori Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#16a085">
                <div class="icon-text">
                    <h3>@ViewBag.d5</h3>
                    <p>Toplam Stok</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#27ae60">

                <div class="icon-text">
                    <h3>@ViewBag.d6</h3>
                    <p>Marka Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#2980b9">

                <div class="icon-text">
                    <h3>@ViewBag.d7</h3>
                    <p>Kritik Seviye</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#8e44ad">

                <div class="icon-text">
                    <h3>@ViewBag.d8</h3>
                    <p>Max Fiyatlı Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>


    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f1c40f">
                <div class="icon-text">
                    <h3>@ViewBag.d9</h3>
                    <p>Min Fiyatlı Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#e67e22">

                <div class="icon-text">
                    <h3>@ViewBag.d12</h3>
                    <p>Max Marka</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#e74c3c">

                <div class="icon-text">
                    <h3>@ViewBag.d10</h3>
                    <p>Buzdolabı Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#95a5a6">

                <div class="icon-text">
                    <h3>@ViewBag.d11</h3>
                    <p>Laptop Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f39c12">
                <div class="icon-text">
                    <h3>@ViewBag.d13</h3>
                    <p>En Çok Satan</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#d35400">

                <div class="icon-text">
                    <h3>@ViewBag.d14</h3>
                    <p>Kasadaki Tutar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#c0392b">

                <div class="icon-text">
                    <h3>@ViewBag.d15</h3>
                    <p>Bugünkü Satşlar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#7f8c8d">

                <div class="icon-text">
                    <h3>@ViewBag.d16</h3>
                    <p>Bugünkü Kasa</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>

MvcOnlineTicariOtomasyon/Views/Statistics/Partial1.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.Classes.GroupClass2>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Departman Personel Sayıları</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Departman</th>
                    <th>Progress Bar</th>
                    <th style="width: 40px">Sayı</th>
                </tr>
            </thead>
            <tbody>
                @{ int sirano = 0;}
                @foreach (var x in Model)
                {
                    <tr>

                        <td>@{sirano++;} @sirano</td>
                        <td>@x.Departmentt</td>
                        <td>
                            @if (x.Number <= 1)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (x.Number == 2)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                </div>
                            }
                            @if (x.Number >= 3)
                            {
                                <div class="progress progress-xs progress-striped active">
                                    <div class="progress-bar bg-success" style="width: 90%"></div>
                                </div>
                            }
                        </td>
                        <td>
                            @if (x.Number <= 1)
                            {
                                <span class="badge bg-danger">@x.Number</span>
                            }
                            @if (x.Number == 2)
                            {
                                <span class="badge bg-warning">@x.Number</span>
                            }
                            @if (x.Number >= 3)
                            {
                                <span class="badge bg-success">@x.Number</span>
                            }

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

MvcOnlineTicariOtomasyon/Views/Statistics/Partial2.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<Current>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Cariler Hover Tablosu</h3>
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ad</th>
                            <th>Soyad</th>
                            <th>Şehir</th>
                            <th>Mail</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                            <tr>
                                <td>@x.CurrentId</td>
                                <td>@x.CurrentName</td>
                                <td>@x.CurrentSurname</td>
                                <td>@x.CurrentCity</td>
                                <td>@x.CurrentMail</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

MvcOnlineTicariOtomasyon/Views/Statistics/Partial3.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<Product>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Ürün Bilgi Tablosu</h3>
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ürün Adı</th>
                            <th>Marka</th>
                            <th>Stok</th>
                            <th>Alış Fiyat</th>
                            <th>Satış Fiyat</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                            <tr>
                                <td>@x.ProductId</td>
                                <td>@x.ProductName</td>
                                <td>@x.ProductBrand</td>
                                <td>@x.ProductStock</td>
                                <td>@x.ProductPurchasePrice ₺</td>
                                <td>@x.ProductSalePrice ₺</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

MvcOnlineTicariOtomasyon/Views/Statistics/SimpleTables.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.Classes.GroupClass>
@{
    ViewBag.Title = "SimpleTables";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Simple Tables</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Hızlı Bakış Tabloları</h1>
                    </div>

                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Kategori Tablosu</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Kategori Adı</th>
                                            <th>Progress Bar</th>
                                            <th style="width: 40px">Oran</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1.</td>
                                            <td>Beyaz Eşya</td>
                                            <td>
                                                <div class="progress progress-xs">
                                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-danger">55%</span></td>
                                        </tr>
                                        <tr>
                                            <td>2.</td>
                                            <td>Küçük Ev Aletleri</td>
                                            <td>
                                                <div class="progress progress-xs">
                                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-warning">70%</span></td>
                                        </tr>
                                        <tr>
                                            <td>3.</td>
                                            <td>Bilgisayar</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-primary" style="width: 30%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-primary">30%</span></td>
                                        </tr>
                                        <tr>
                                            <td>4.</td>
                                            <td>Mobilya</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-success" style="width: 90%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-success">90%</span></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                        @Html.Action("Partial1", "Statistics")

                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Müşteri Şehir Tablosu</h3>
                                <div class="card-tools">
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Şehir</th>
                                            <th>Progress Bar</th>
                                            <th style="width: 40px">Adet</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{ int sirano = 0;}
                                        @foreach (var x in Model)
                                        {
                                            <tr>

                                                <td>@{sirano++;} @sirano</td>
                                                <td>@x.City</td>
                                                <td>
                                                    @if (x.Total == 1)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                        </div>
                                                    }
                                                    @if (x.Total == 2)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                        </div>
                                                    }
                                                    @if (x.Total == 3)
                                                    {
                                                        <div class="progress progress-xs progress-striped active">
                                                            <div class="progress-bar bg-success" style="width: 90%"></div>
                                                        </div>
                                                    }
                                                </td>
                                                <td>
                                                    @if (x.Total == 1)
                                                    {
                                                        <span class="badge bg-danger">@x.Total</span>
                                                    }
                                                    @if (x.Total == 2)
                                                    {
                                                        <span class="badge bg-warning">@x.Total</span>
                                                    }
                                                    @if (x.Total == 3)
                                                    {
                                                        <span class="badge bg-success">@x.Total</span>
                                                    }

                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                        @Html.Action("Partial4", "Statistics")
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
                @Html.Action("Partial2", "Statistics")
                <!-- /.row -->
                @Html.Action("Partial3", "Statistics")
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
</body>
</html>